services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env.backend
    volumes:
      - ./backend/model_artifacts:/app/model_artifacts
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env.frontend
    depends_on:
      - backend

volumes:
  redis_data:
