services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env.backend
    volumes:
      - ./backend/model_artifacts:/app/model_artifacts


  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env.frontend
    depends_on:
      - backend
